### ISSUE TITLE
Freezing when using Swap node left/right when moving in front of or behind something with multiple node directions (ex: a montage)

### ISSUE THREAD

**Issue by bitb22** [TheHerobrine/ElectronicNodes#9] opened 2019-11-04 20:45 UTC
**Describe the bug**
When Swap node left/right on something like a print string, is the user moves it to code with multiple node directions (ex montage: completed, interrupted, on notify begin, ect..) the project will crash

**To Reproduce**
1. Go to a blueprint
2. Click on a print string
3. use control shift and the left or right arrow to move the print string in front of or behind a montage

**Expected behavior**
Swap node left/right works on code with multiple nodes directions 

**Screenshots**
Swap node left/right crashes on code with multiple nodes directions 

**Environment (please complete the following information):**
 - Unreal Engine version: UE 4.22
 - Operating System: Windows 64bits

**Additional context**
The problem seems to get worse with more stuff present (if the engine is working harder)
had a repro rate of 5/5
Tested it on another users computer, same result. Although we were working on the same project. 
Feel free to reach out - benbitme22@gmail.com or discord bitb#2584

**Comment by TheHerobrine** [comment] 2019-11-04 22:23
@bitb22 Hello! Thank you very much for spotting this bug, I'm really sorry about it 😕...

I can't manage to reproduce, a "montage" seems to be an animation-related thing and I'm not very used to it. Could you please provide me some screens of such blueprint, as well as a copy of the error message if possible?

If it's really specific about animation blueprint, it may have already been solved with this issue: https://github.com/TheHerobrine/ElectronicNodes/issues/8 (it appears that's animation were not handled very well, it's fixed now). But for me to confirm it, I have to reproduce it on the current version of the plugin 😅...

Also, is this a critical bug (that need to be fixed asap), or could you wait for the next version (in about a week)? I would totally understand if it's a critical bug for you!

**Comment by bitb22** [comment] 2019-11-05 00:49
Looks like the repro rate is less than 5/5 and there is more steps required to repro the steps.

**Comment by TheHerobrine** [comment] 2019-11-07 23:50
After discussing on Discord, seems that I can add an extra security to prevent that kind of bug.
I couldn't reproduce, so I'll leave the issue open after the release of the next version of the plugin, just to be sure no one reproduce it.

The next version of the plugin should be out next week hopefully! (I'm a bit stuck with [this feature](https://github.com/TheHerobrine/ElectronicNodes/issues/7), so it takes longer than expected...)

**Closed** 2019-11-10 02:48 UTC
Labels: bug, ready
