### ISSUE TITLE
Failed to rebuild as a project plugin

### ISSUE THREAD

**Issue by lucasdlk** [TheHerobrine/ElectronicNodes#12] opened 2019-12-16 12:15 UTC
**Describe the bug**
I wanted to rebuild the plugin as a project plugin. It worked some days ago but now it seems it can't find 'AnimGraphConnectionDrawingPolicy.cpp'

here is the error log : 
``D:\git\Altexp\ALTEXP_UE4\Plugins\ElectronicNodes\Source\ElectronicNodes\Private\ENAnimGraphConnectionDrawingPolicy.h(8): fatal error C1083: Impossible d'ouvrir le fichier include�: 'AnimGraphConnectionDrawingPolicy.cpp'�: No such file or directory.``

**To Reproduce**
1. Copy "ElectronicNodes" folder from engine plugins to project plugins
2. Try to rebuild from source

**Environment (please complete the following information):**
 - Unreal Engine version: 4.23
 - Operating System: Windows 10 64bits

**Comment by TheHerobrine** [comment] 2019-12-16 23:39
@lucasdlk Hum, that's pretty weird... This file should be accessible from the engine since it is required from the ElectronicNodes.Build.cs...

I can't reproduce, do you use a custom engine?

## Solution 1
Did you just rebuild your project rebuild your project from Visual Studio? If not, could you try it?
(by right clicking on your project under the "Games" folder, then "Generate")

![image](https://user-images.githubusercontent.com/4563971/70951161-e17a6480-2062-11ea-864c-a217790d8bb7.png)

## Solution 2
Could you try to copy/paste the `AnimGraphConnectionDrawingPolicy.cpp` directly into the plugin folder?
You'll have to copy this file:
`Engine/U4/Source/Editor/AnimationBlueprintEditor/Private/AnimGraphConnectionDrawingPolicy.cpp`
To
`Game/[your_game]/Plugins/ElectronicNodes/Private/AnimGraphConnectionDrawingPolicy.cpp`
And then, try to rebuild it.

## Solution 3 (temporary)
If you do not use AnimationGraph, you can delete:
- the file `ENAnimGraphConnectionDrawingPolicy.cpp` from `ElectronicNodes/Private`
- the file `ENAnimGraphConnectionDrawingPolicy.h` from `ElectronicNodes/Private`
- the lines
```cpp
#include "ENAnimGraphConnectionDrawingPolicy.h"
```
and
```cpp
if (Schema->IsA(UAnimationGraphSchema::StaticClass()))
{
	if (ElectronicNodesSettings.ActivateOnAnimation)
	{
		return new FENAnimGraphConnectionDrawingPolicy(InBackLayerID, InFrontLayerID, ZoomFactor, InClippingRect, InDrawElements, InGraphObj);
	}
	return nullptr;
}
```
from the `ENConnectionDrawingPolicy.cpp` file of `ElectronicNodes/Private`
And then, try to rebuild it.

---

Please tell me what works for you and what does not. And if you use a custom engine or a standard engine, and it's the last version (4.23.1 for the engine, 2.2 for the plugin). Thank you very much!

*PS: Content de voir que des français utilisent mon plugin :D !*

**Comment by lucasdlk** [comment] 2019-12-17 08:17
I think my engine was missing some files.
After a verify from the launcher, no more errors. My bad !

**Comment by TheHerobrine** [comment] 2019-12-17 19:39
Thank you very much for having kept me posted on! So I'll close the issue ;)

**Closed by TheHerobrine** 2019-12-17 19:39 UTC
Labels: bug

**Comment by chacobo** [comment] 2022-03-24 02:10
I'm having the same issue with UE4.27. In fact the .cpp's are not there in the engine plugin folder. Verifying install didn't resolve the problem.

![image](https://user-images.githubusercontent.com/50167935/159826768-93a35f19-a22b-4c96-a95c-3a2c227d0326.png)

**Comment by chacobo** [comment] 2022-03-24 05:06
"Engine Source Code" was not selected in UE install. Fixed!
